name: ci

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Build test image
        run: "cd test && docker build -t tronikel/conflict-marker.nvim-test ."

      - name: Run tests
        run: "./run_tests.sh"

